PROJECT:=IEEEConference

include makefile-latex/latex-std-dependence.mk
DEPS_MAIN_TEX:=${CLSS_IEEE_CONFERENCE}
DEPS_FIGS_TEX:=${STYS_MINIMUS} ${CLSS_STANDALONE_SILICON}

LATEX_MAIN_COMPILER:=-pdf

include makefile-latex/makefile-latex.mk
